// <auto-generated />
using ConvTeploobmen.Client.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConvTeploobmen.App.Migrations
{
    [DbContext(typeof(ConvTeploobDbConvtext))]
    [Migration("20240409215629_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ConvTeploobmen.Client.DataBase.Gas", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("KinematicViscosity")
                        .HasColumnType("REAL");

                    b.HasKey("Name");

                    b.ToTable("Gases");
                });

            modelBuilder.Entity("ConvTeploobmen.Client.DataBase.Prandtl", b =>
                {
                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Temperature");

                    b.ToTable("Prandtls");
                });
#pragma warning restore 612, 618
        }
    }
}
