// <auto-generated />
using ConvTeploobmen.Client.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConvTeploobmen.Client.Migrations
{
    [DbContext(typeof(ConvTeploobDbContext))]
    partial class ConvTeploobDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ConvTeploobmen.App.DataBase.AttackAngle", b =>
                {
                    b.Property<int>("Degree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Degree");

                    b.ToTable("AttackAngles");

                    b.HasData(
                        new
                        {
                            Degree = 10,
                            Value = 0.41999999999999998
                        },
                        new
                        {
                            Degree = 20,
                            Value = 0.52000000000000002
                        },
                        new
                        {
                            Degree = 30,
                            Value = 0.67000000000000004
                        },
                        new
                        {
                            Degree = 40,
                            Value = 0.78000000000000003
                        },
                        new
                        {
                            Degree = 50,
                            Value = 0.88
                        },
                        new
                        {
                            Degree = 60,
                            Value = 0.93999999999999995
                        },
                        new
                        {
                            Degree = 70,
                            Value = 0.97999999999999998
                        },
                        new
                        {
                            Degree = 80,
                            Value = 1.0
                        },
                        new
                        {
                            Degree = 90,
                            Value = 1.0
                        });
                });

            modelBuilder.Entity("ConvTeploobmen.Client.DataBase.ThermalConductivityKoeffs", b =>
                {
                    b.Property<string>("GasName")
                        .HasColumnType("TEXT");

                    b.Property<double>("koeff1")
                        .HasColumnType("REAL");

                    b.Property<double>("koeff2")
                        .HasColumnType("REAL");

                    b.Property<double>("koeff3")
                        .HasColumnType("REAL");

                    b.HasKey("GasName");

                    b.ToTable("ThermalConductancesKoeffs");

                    b.HasData(
                        new
                        {
                            GasName = "O2",
                            koeff1 = -2.9999999999999997E-08,
                            koeff2 = 9.0000000000000006E-05,
                            koeff3 = 0.024250000000000001
                        },
                        new
                        {
                            GasName = "CO2",
                            koeff1 = 2.0000000000000001E-10,
                            koeff2 = 8.0000000000000007E-05,
                            koeff3 = 0.0141
                        },
                        new
                        {
                            GasName = "N2",
                            koeff1 = -2E-08,
                            koeff2 = 6.0000000000000002E-05,
                            koeff3 = 0.025250000000000002
                        },
                        new
                        {
                            GasName = "H2O",
                            koeff1 = 7.0000000000000005E-08,
                            koeff2 = 6.9999999999999994E-05,
                            koeff3 = 0.016789999999999999
                        });
                });

            modelBuilder.Entity("ConvTeploobmen.Client.DataBase.ViscosityKoeffs", b =>
                {
                    b.Property<string>("GasName")
                        .HasColumnType("TEXT");

                    b.Property<double>("koeff1")
                        .HasColumnType("REAL");

                    b.Property<double>("koeff2")
                        .HasColumnType("REAL");

                    b.Property<double>("koeff3")
                        .HasColumnType("REAL");

                    b.HasKey("GasName");

                    b.ToTable("ViscositiesKoeffs");

                    b.HasData(
                        new
                        {
                            GasName = "O2",
                            koeff1 = 6E-11,
                            koeff2 = 9.9999999999999995E-08,
                            koeff3 = 1.0000000000000001E-05
                        },
                        new
                        {
                            GasName = "CO2",
                            koeff1 = 3.9999999999999998E-11,
                            koeff2 = 7.0000000000000005E-08,
                            koeff3 = 5.0000000000000004E-06
                        },
                        new
                        {
                            GasName = "N2",
                            koeff1 = 6E-11,
                            koeff2 = 9.9999999999999995E-08,
                            koeff3 = 1.0000000000000001E-05
                        },
                        new
                        {
                            GasName = "H2O",
                            koeff1 = 2.0000000000000001E-10,
                            koeff2 = 8.9999999999999999E-08,
                            koeff3 = 1.0000000000000001E-05
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
